name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up JDK 21 with Gradle cache
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      # 3. Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build and run unit tests
      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      # 5. Set up Android SDK & Emulator
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest

      # 6. Build debug APK
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 7. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
