name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up JDK 21 with Gradle cache
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: |
            **/*.gradle*
            **/gradle-wrapper.properties

      # 3. Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build project & run unit tests
      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      # 5. Build debug APK
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 6. Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

instrumentation-tests:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      api-level: [33, 34, 36] # use 33+ (lighter + more stable)
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Instrumented Tests on API ${{ matrix.api-level }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: google_apis
        arch: x86_64
        profile: Nexus 6
        emulator-options: -no-snapshot -noaudio -no-boot-anim -camera-back none
        script: ./gradlew connectedAndroidTest

